---
---

<link rel="stylesheet" href="styles.css" type="text/css">

***

I'm a full stack data scientist who works predominantly with financial, economic, and public opinion data. I'm currently a senior data scientist at [Morning Consult](https://morningconsult.com/) in Washington, D.C., where I help clients leverage public opinion data to make better decisions, improve the processes by which we do market research, and rapidly prototype data products to better deliver insights from our brand tracking platform. Previously, I investigated questions related to bank lending and monetary policy as a Senior Research Assistant at the [Federal Reserve Board](https://www.federalreserve.gov/), where I contributed to division research (chiefly related to interest rates, bank lending standards, and financial conditions) and operationalized new and existing data sources into production-ready monitors. 

I graduated from the [Johns Hopkins University School of Advanced International Studies](https://www.sais-jhu.edu/mief#overview) (SAIS) with a masters degree in International Economics and Finance (MIEF) in 2017, a rigorous, STEM-accredited quantitative econometrics program. During my graduate studies, I worked as a research assistant for Dr. Jaime Marquez using Monte Carlo methods and FIML models to investigate interdependent Taylor Rules. I also hold a [Certificate in Data Science](https://scs.georgetown.edu/programs/375/certificate-in-data-science/) from Georgetown University.

I work in both Python and R interchangeably in my work, but I am first and foremost an avid R enthusiast. I teach several R courses to students in the MIEF program at SAIS as an Adjunct Lecturer and have taught introductory R as a part of onboarding new division RAs at the Federal Reserve Board. I am also an Adjunct Lecturer on the Georgetown University School of Continuing Studies Data Science certificate faculty, and co-teach a course on creating value from survey data.

My resume is available [here](files/berry_cv.pdf).
