---
title: "Research"
output:
  html_document:
    theme: sandstone
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***

### Analyzing GSIB Surcharges using the Y-15

[How Do U.S. Global Systemically Important Banks Lower Their Capital Surcharges?](https://www.federalreserve.gov/econres/notes/feds-notes/how-do-us-global-systemically-important-banks-lower-their-capital-surcharges-20200131.htm)

Prior to leaving the Federal Reserve Board (in the spring of 2020), I contributed to the analytics pipeline for work exploring how globally systemic important banks (GSIBs, or in layman's terms, very large banks) lower the surcharges they face for holding the amounts of capital they do. I was predominantly involved in sourcing the data and building an ingestiion pipeline from publically available NIC files for use in regression frameworks in R and STATA. 

### Analyzing Net Interest Margins (NIMs) across Monetary Policy Tightening Episodes

[Changes in Monetary Policy and Banks' Net Interest Margins](https://www.federalreserve.gov/econres/notes/feds-notes/changes-in-monetary-policy-and-banks-net-interest-margins-a-comparison-20190419.htm)

While at the Federal Reserve Board, I co-authored a FEDS Note analyzing changes in net interest margins (NIMs) at banks relative to monetary policy tightening episodes over the past three decades. I wrote all the code used to perform the analysis, implementing cumulative decompositions using bank balance sheet data and developing all data visualizations in R.

### Long-run Exchange Rate Forecasting

[The Role of Theory-Motivated Fundamentals in Long-Run Exchange Rate Forecasting](files/exchange_rate_forecasting.pdf)

For my Master's Capstone, I examined the role of “fundamentals” (or theory) in long-term exchange rate forecasting, and found that the inclusion of structural components, such as the relative price ratio, improved the accuracy of long-term exchange rate forecasts. I made novel use of an exceptionally long time-series dataset, and explored other forecasting techniques using a Vector Error Correction Model (VECM) and leveraged the use of information in the forward market for exchange rates.

***

### Predicting Global GDP Convergence

[Global GDP Convergence Estimation](files/global_gdp_convergence.pdf)

Using two approaches--"sigma" (advanced by Boyle and McCarthy (1999)) and vector autoregression (VAR) modeling--I explore the degree to which GDP has converged across countries in the past half-century. Results from both approaches support evidence of convergence across both developed and developing economies, and VARs provide an opportunity to forecast when convergence might occur, holding current trends constant, though the degree of and time of convergence are highly sensitive to assumptions made about lag structures in the VAR and choice of country groupings. 

***

### Modeling Exchange Rate Pass-Through

[Assessing the Impact of Exchange Rate Pass-Through on the U.S. Dollar](files/pass_through.pdf)

Expounding largely on the work of Gruber, McCallum, and Vigfusson (2016), I empirically evaluate the degree of exchange rate pass-through on the U.S. Dollar, and find evidence that pass-through of exchange rate fluctuations has declined over the past few decades. This finding is robust to changes in specification explored in the analysis.

***

### Interdependent Taylor Rules

[International Interest Rate Interdependence](files/taylor_rule.pdf)
[Presentation slides](files/taylor_rule_presentation.pdf)

Recognizing that monetary policy cannot occur in a vacuum in an increasingly globalized economy, I evaluate the extent of international interdependence between developed economies in setting monetary policy using a modified Taylor Rule. Using vector autogression (VAR), full-information maximum likelihood (FIML) and Monte Carlo methods to model the degree of interdependence of country-level monetary policy rules that are set with respect to other countries and find evidence of interedependence. I find that interdependence is largely country-specific, and accounting for it can improve the quality of monetary policy rules for assessing the trajectory of monetary policy per the interest rate environment. This represents the culmination of my work as a research assistant under the direction of Dr. Jaime Marquez.

***